// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eguxvxglvwfylgwlbcdy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVndXh2eGdsdndmeWxnd2xiY2R5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1OTg1OTcsImV4cCI6MjA3MTE3NDU5N30.6kYEYjZvOMdkIafr-vYpK7mEMWxgfMKD81FzxZMMqhE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});